# This is a basic workflow to help you get started with Actions

name: Build model file

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the "master" branch
  push:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      # Building UnifiedData.rbxm
      - name: cargo install rojo
        uses: baptiste0928/cargo-install@v2.0.0
        with:
          crate: rojo
      - name: build UnifiedData.rbxm
        run: rojo build --output UnifiedData.rbxm
      - name: Archive build artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: UnifiedData.rbxm
